# Key Bindings
# key name refer to `xev` or `wev` command output,
# mod keys name: super,ctrl,alt,shift,none

# reload config
bind=SUPER,r,reload_config

# apps
bind=SUPER,space,spawn,rofi -show drun -theme /home/gentoo/.local/share/mango-dotfiles/config/rofi/styles.rasi
bind=SUPER,v,spawn_shell,cliphist list | rofi -dmenu -theme /home/gentoo/.local/share/mango-dotfiles/config/rofi/styles.rasi | cliphist decode | wl-copy
bind=SUPER,Return,spawn,foot
bind=SUPER,e,spawn,foot -e nvim
bind=SUPER,b,spawn,/home/gentoo/.local/bin/zen
bind=SUPER,f,spawn,foot -e /home/gentoo/.local/bin/nnn
bind=SUPER,o,spawn,obsidian

# screenshots
bind=NONE,Print,spawn_shell,grim - | wl-copy --type image/png
bind=SHIFT,Print,spawn_shell,grim -g "$(slurp)" - | wl-copy --type image/png

# night shift toggle
bind=SUPER,y,spawn,/home/gentoo/.local/bin/mango-nightlight toggle
bind=ALT,y,spawn,/home/gentoo/.local/bin/mango-nightlight off

# exit
bind=SUPER,m,quit
bind=SUPER,x,killclient,

# switch keyboard layout
bindl=alt,shift_l,switch_keyboard_layout

# switch window focus
bind=SUPER,Tab,focusstack,next
bind=ALT,Left,focusdir,left
bind=ALT,Right,focusdir,right

# swap window
bind=ALT+SHIFT,Up,exchange_client,up
bind=ALT+SHIFT,Down,exchange_client,down
bind=ALT+SHIFT,Left,exchange_client,left
bind=ALT+SHIFT,Right,exchange_client,right

# switch window status
bind=SUPER,g,toggleglobal,
bind=ALT,Tab,toggleoverview,
bind=ALT,backslash,togglefloating,
bind=ALT,a,togglemaximizescreen,
bind=ALT,f,togglefullscreen,
bind=ALT+SHIFT,f,togglefakefullscreen,
bind=ALT,i,minimized,
bind=ALT,o,toggleoverlay,
bind=ALT+SHIFT,I,restore_minimized
bind=ALT,z,toggle_scratchpad

# scroller layout
bind=ALT,e,set_proportion,1.0
bind=ALT,x,switch_proportion_preset,
bind=alt+super+ctrl,Left,scroller_stack,left
bind=alt+super+ctrl,Right,scroller_stack,right
bind=alt+super+ctrl,Up,scroller_stack,up
bind=alt+super+ctrl,Down,scroller_stack,down

# dwindle layout(manual split mode)
bind=alt+shift,Return,dwindle_toggle_split_direction

# switch layout
bind=SUPER,n,switch_layout

# tag switch
bind=SUPER,Left,viewtoleft_have_client,0
bind=SUPER,Right,viewtoright_have_client,0

bind=CTRL+SUPER,Left,tagtoleft,0
bind=CTRL+SUPER,Right,tagtoright,0

bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0

# tag: move client to the tag and focus it
# tagsilent: move client to the tag and not focus it
# bind=Alt,1,tagsilent,1
bind=CTRL+SUPER,1,tag,1,0
bind=CTRL+SUPER,2,tag,2,0
bind=CTRL+SUPER,3,tag,3,0
bind=CTRL+SUPER,4,tag,4,0
bind=CTRL+SUPER,5,tag,5,0
bind=CTRL+SUPER,6,tag,6,0
bind=CTRL+SUPER,7,tag,7,0
bind=CTRL+SUPER,8,tag,8,0
bind=CTRL+SUPER,9,tag,9,0

# monitor switch
bind=shift+ctrl+super,Left,focusmon,left
bind=shift+ctrl+super,Right,focusmon,right
bind=SUPER+Alt,Left,tagmon,left
bind=SUPER+Alt,Right,tagmon,right

# gaps
bind=ALT+SHIFT,X,incgaps,1
bind=ALT+SHIFT,Z,incgaps,-1
bind=ALT+SHIFT,R,togglegaps

# resizewin
bind=CTRL+ALT,Up,resizewin,+0,-50
bind=CTRL+ALT,Down,resizewin,+0,+50
bind=CTRL+ALT,Left,resizewin,-50,+0
bind=CTRL+ALT,Right,resizewin,+50,+0

# Mouse Button Bindings
# btn_left and btn_right can't bind none mod key
mousebind=SUPER,btn_left,moveresize,curmove
#mousebind=NONE,btn_middle,togglemaximizescreen,0
mousebind=SUPER,btn_right,moveresize,curresize


# Axis Bindings
axisbind=SUPER,UP,viewtoleft_have_client
axisbind=SUPER,DOWN,viewtoright_have_client
